# Знакомство с PyTorch

**PyTorch** -- это фреймворк для машинного обучения для языка Python с открытым исходным кодом, разрабатываемый под покровительством Facebook.  

Используется для решения различных задач в области компьютерного зрения, обработки естественного языка и т. д.  

Первый релиз PyTorch вышел в 2016 году, и с тех пор он занимает прочную нишу в области глубокого обучения.  

Как утверждает [документация](https://pytorch.org/docs/stable/index.html) по PyTorch, он является науно-вычислительным пакетом, который предоставляет следующие возможности:
* тензорные вычисления с возможностью распараллеливания их на GPU (имеется поддержка множества GPU)  
* развитые алгоритмы глубокого обучения, обеспечивающие максимальную гибкость и скорость выполнения

Вокруг PyTorch за время его существования выстроилась целая экосистема, состоящая из различных смежных по области применения библиотек: Fast.ai (создана для упрощения создания моделей), Flair (для обработки естественного языка и т. д.)  

В первую очередь, PyTorch фокусируется на простоте использования и позволяет пользователям с базовыми навыками программирования создавать свои проекты по глубокому обучению. Это возможно благодаря тому, что он поддерживает питонский стиль написания кода.

Также явным преимуществом PyTorch перед другими фреймворками является простота отладки.  
В процессе отладки модели, написанных на других фреймворках, не всегда понятно, что пошло не так.
Также PyTorch тесно интегрирован с Python и основыми библиотеками для Data Science для него: NumPy, SciPy и т. д.  

Скрость выполнения алгоритмов глубокого обучения на PyTorch обеспечивает высокопроизводительный C++ API

## Работа с тензорами

Современные модели глубокого обучения, позволяющие решать множество задач (в особенности в компьютерном зрении), по сути, находят сложные представления в данных. Эти представления представляют собой множества чисел с плавяющей запятой.

Основной структурой в PyTorch, позволяющей хранить множества чисел с плавающей запятой, являются **тензоры**

В рамках глубокого обучения под тензорами понимаются, прежде всего, многомерные массивы

In [ ]:
# создадим первые тензоры на PyTorch
import torch

# тензоры можно создавать на основе списков Python
first_list = [3, 6, 9, 11, 13]
first_tensor = torch.Tensor(first_list)
type(first_tensor)

torch.Tensor

In [ ]:
first_tensor

tensor([ 3.,  6.,  9., 11., 13.])

In [ ]:
# также тензоры можно создавать на основе массивов numpy
import numpy as np
numpy_array = np.array([1, 3, 5, 7, 9])
print(type(numpy_array))
print(numpy_array)

torch_array = torch.from_numpy(numpy_array)
print(type(torch_array))
print(torch_array)

<class 'numpy.ndarray'>
[1 3 5 7 9]
<class 'torch.Tensor'>
tensor([1, 3, 5, 7, 9])


In [ ]:
# также можно задавать тензоры с произвольными значениями
# создадим тензор, состоящий из одних нулей
zeros_tensor = torch.zeros(100)
zeros_tensor

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [ ]:
# создадим тензор, состоящий из одних единиц
ones_tensor = torch.ones(100)
ones_tensor

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# создадим тензор, состоящий из чисел, находящихся в диапазоне между 0 и 1
random_tensor = torch.rand(100)
random_tensor

tensor([0.2751, 0.9990, 0.0022, 0.7215, 0.6840, 0.8357, 0.0185, 0.0909, 0.2739,
        0.4333, 0.8337, 0.8901, 0.5461, 0.2022, 0.4735, 0.2683, 0.3246, 0.6216,
        0.7712, 0.1455, 0.8784, 0.2192, 0.7056, 0.3654, 0.6369, 0.2966, 0.8791,
        0.9863, 0.2164, 0.2044, 0.7606, 0.7282, 0.9896, 0.9536, 0.3321, 0.8137,
        0.6287, 0.9584, 0.0983, 0.3885, 0.9341, 0.6831, 0.8065, 0.5756, 0.8666,
        0.8912, 0.9161, 0.4128, 0.2122, 0.4489, 0.6574, 0.1490, 0.0672, 0.3848,
        0.8919, 0.1021, 0.7542, 0.0140, 0.5991, 0.9718, 0.4510, 0.4082, 0.3678,
        0.5440, 0.5995, 0.7999, 0.8146, 0.7851, 0.4412, 0.6562, 0.6358, 0.9718,
        0.9992, 0.1441, 0.6823, 0.2853, 0.6269, 0.5221, 0.0060, 0.4872, 0.1417,
        0.4197, 0.5757, 0.7937, 0.3249, 0.1248, 0.9111, 0.9497, 0.5053, 0.4654,
        0.2756, 0.5733, 0.0346, 0.8844, 0.3592, 0.3163, 0.5642, 0.5194, 0.5041,
        0.0782])

In [ ]:
# указанными выше способами можно задвать тензоры произвольных размерностей
second_random_tensor = torch.rand(10, 10)
second_random_tensor

tensor([[0.5975, 0.9394, 0.2113, 0.5702, 0.6497, 0.1959, 0.1030, 0.1789, 0.8238,
         0.7053],
        [0.6957, 0.8898, 0.6837, 0.2725, 0.7376, 0.8744, 0.3918, 0.2417, 0.4258,
         0.7458],
        [0.9428, 0.6205, 0.2033, 0.5957, 0.4082, 0.3668, 0.0409, 0.6300, 0.3279,
         0.6134],
        [0.9620, 0.8066, 0.7415, 0.6177, 0.8454, 0.5004, 0.7828, 0.4555, 0.3764,
         0.0274],
        [0.9502, 0.5555, 0.6149, 0.0160, 0.2817, 0.7244, 0.4054, 0.0716, 0.1932,
         0.5715],
        [0.4587, 0.2209, 0.0956, 0.9214, 0.5821, 0.2115, 0.0914, 0.1561, 0.9681,
         0.6830],
        [0.7585, 0.6813, 0.0646, 0.5326, 0.9388, 0.8326, 0.4190, 0.8188, 0.3782,
         0.1046],
        [0.8975, 0.4423, 0.1444, 0.7944, 0.2471, 0.6912, 0.4557, 0.4619, 0.8177,
         0.9834],
        [0.5816, 0.2750, 0.3250, 0.7775, 0.6497, 0.0155, 0.5773, 0.9708, 0.7614,
         0.6352],
        [0.5283, 0.4844, 0.9226, 0.9118, 0.6999, 0.0562, 0.0584, 0.2718, 0.9658,
         0.3305]])

In [ ]:
third_random_tensor = torch.rand(1, 3, 416, 416)
third_random_tensor

tensor([[[[0.4068, 0.8029, 0.4180,  ..., 0.7649, 0.5333, 0.0613],
          [0.5534, 0.8308, 0.2009,  ..., 0.2986, 0.2571, 0.1600],
          [0.8308, 0.7052, 0.9179,  ..., 0.9723, 0.1329, 0.5378],
          ...,
          [0.7999, 0.2504, 0.8587,  ..., 0.3699, 0.4507, 0.7639],
          [0.5440, 0.1362, 0.5550,  ..., 0.8522, 0.2195, 0.0793],
          [0.8493, 0.8123, 0.6326,  ..., 0.5751, 0.6147, 0.2737]],

         [[0.6437, 0.2779, 0.3688,  ..., 0.0056, 0.9003, 0.6343],
          [0.8424, 0.4626, 0.0407,  ..., 0.1147, 0.3591, 0.8591],
          [0.9355, 0.0085, 0.7302,  ..., 0.1879, 0.4490, 0.6659],
          ...,
          [0.1344, 0.2245, 0.1373,  ..., 0.5187, 0.7793, 0.6198],
          [0.4748, 0.9851, 0.5847,  ..., 0.1135, 0.2221, 0.6462],
          [0.8671, 0.9402, 0.1691,  ..., 0.6532, 0.2414, 0.4051]],

         [[0.9789, 0.9879, 0.8707,  ..., 0.3728, 0.1265, 0.7666],
          [0.1014, 0.0686, 0.5172,  ..., 0.9644, 0.9381, 0.0500],
          [0.8194, 0.5900, 0.6096,  ..., 0

In [ ]:
third_random_tensor_ = torch.rand(3, 416, 416)
third_random_tensor_.shape

torch.Size([3, 416, 416])

In [ ]:
third_random_tensor_ = third_random_tensor_.unsqueeze(0)
third_random_tensor_.shape

torch.Size([1, 3, 416, 416])

In [ ]:
# чтобы узнать размерность тензора, нужно вызвать атрибу тsize у тензора
third_random_tensor.shape

torch.Size([1, 3, 416, 416])

In [ ]:
# к элементам тензора можно осуществлять доступ по индексам по аналогии со списками в Python
fourth_random_tensor = torch.rand(9, 9)
fourth_random_tensor

tensor([[0.7665, 0.0892, 0.9050, 0.6813, 0.1263, 0.6049, 0.2611, 0.8164, 0.4995],
        [0.4080, 0.7917, 0.0423, 0.9952, 0.3499, 0.8089, 0.7641, 0.7789, 0.7849],
        [0.9780, 0.1594, 0.0080, 0.8827, 0.8100, 0.4773, 0.8812, 0.9806, 0.4461],
        [0.1710, 0.2865, 0.4673, 0.1794, 0.6505, 0.8497, 0.0192, 0.9919, 0.9213],
        [0.3875, 0.8660, 0.5253, 0.7699, 0.7755, 0.8268, 0.2177, 0.0719, 0.1263],
        [0.9616, 0.2189, 0.5198, 0.6300, 0.8995, 0.8249, 0.8351, 0.6320, 0.5761],
        [0.2193, 0.3651, 0.2742, 0.8447, 0.1842, 0.3342, 0.8408, 0.9213, 0.3516],
        [0.1926, 0.0442, 0.4953, 0.4702, 0.1771, 0.1749, 0.9968, 0.8422, 0.1115],
        [0.3603, 0.1014, 0.9937, 0.2538, 0.8686, 0.0500, 0.4604, 0.0622, 0.5186]])

In [ ]:
print(fourth_random_tensor[0])
print("\n")
print(fourth_random_tensor[0][0])
print("\n")
print(fourth_random_tensor[1:8:2][1:8:2])
print("\n")
print(fourth_random_tensor[-6:-1:2])

tensor([0.7665, 0.0892, 0.9050, 0.6813, 0.1263, 0.6049, 0.2611, 0.8164, 0.4995])


tensor(0.7665)


tensor([[0.1710, 0.2865, 0.4673, 0.1794, 0.6505, 0.8497, 0.0192, 0.9919, 0.9213],
        [0.1926, 0.0442, 0.4953, 0.4702, 0.1771, 0.1749, 0.9968, 0.8422, 0.1115]])


tensor([[0.1710, 0.2865, 0.4673, 0.1794, 0.6505, 0.8497, 0.0192, 0.9919, 0.9213],
        [0.9616, 0.2189, 0.5198, 0.6300, 0.8995, 0.8249, 0.8351, 0.6320, 0.5761],
        [0.1926, 0.0442, 0.4953, 0.4702, 0.1771, 0.1749, 0.9968, 0.8422, 0.1115]])


In [ ]:
# можно произвольно менять элементы тензора
fifth_random_tensor = torch.rand(5)
fifth_random_tensor

tensor([0.6916, 0.3759, 0.5650, 0.1743, 0.4069])

In [ ]:
fifth_random_tensor[0] = 1
fifth_random_tensor

tensor([1.0000, 0.3759, 0.5650, 0.1743, 0.4069])

In [ ]:
# можно задавать числовой тип в тензорах при их создании с помощью аргумента dtype
# по умолчанию все числа в тензорах хранятся в формате float32
fifth_random_tensor.dtype

torch.float32

In [ ]:
float16_random_tensor = torch.rand(10, dtype=torch.float16)
float16_random_tensor

tensor([0.3335, 0.9888, 0.4961, 0.8198, 0.0107, 0.6235, 0.2954, 0.7803, 0.5386,
        0.7783], dtype=torch.float16)

In [ ]:
# можно изменять тип тензора с момощью метода to()
print(fifth_random_tensor.dtype)
fifth_random_tensor = fifth_random_tensor.to(dtype=torch.float64)
print(fifth_random_tensor.dtype)

torch.float32
torch.float64


In [ ]:
# в PyTorch имеется множество методов, предоставляющих операции над тензорами
# все они описаны в подробной документации: https://pytorch.org/docs/stable/tensors.html

# арифметические операции операции
tensor_1 = torch.Tensor([[6, 7], [9, 11]])
tensor_2 = torch.Tensor([[2, 4],[6, 8]])

print(tensor_1 + tensor_2)
print("\n")
print(tensor_1 - tensor_2)
print("\n")
print(tensor_1 * tensor_2)
print("\n")
print(tensor_1 / tensor_2)
print("\n")
print(tensor_1 ** 2 + tensor_2 * 100 - 10)
print("\n")
print(tensor_1 ** 0.5 + tensor_2 ** 0.1)

tensor([[ 8., 11.],
        [15., 19.]])


tensor([[4., 3.],
        [3., 3.]])


tensor([[12., 28.],
        [54., 88.]])


tensor([[3.0000, 1.7500],
        [1.5000, 1.3750]])


tensor([[226., 439.],
        [671., 911.]])


tensor([[3.5213, 3.7944],
        [4.1962, 4.5478]])


In [ ]:
# математические функции
tensor_3 = torch.tensor([10, 20, 30, 40, 50])

print(torch.sin(tensor_3))
print("\n")

print(torch.cos(tensor_3))
print("\n")

print(torch.tan(tensor_3))
print("\n")

print(torch.atan(tensor_3))
print("\n")

print(torch.square(tensor_3))
print("\n")

print(torch.add(tensor_3, 10))
print("\n")

print(torch.log10(tensor_3))
print("\n")

print(torch.pow(tensor_3, 100))
print("\n")

print(torch.exp(tensor_3))
print("\n")

print(torch.neg(tensor_3))
print("\n")

print(torch.abs(tensor_3))

tensor([-0.5440,  0.9129, -0.9880,  0.7451, -0.2624])


tensor([-0.8391,  0.4081,  0.1543, -0.6669,  0.9650])


tensor([ 0.6484,  2.2372, -6.4053, -1.1172, -0.2719])


tensor([1.4711, 1.5208, 1.5375, 1.5458, 1.5508])


tensor([ 100,  400,  900, 1600, 2500])


tensor([20, 30, 40, 50, 60])


tensor([1.0000, 1.3010, 1.4771, 1.6021, 1.6990])


tensor([0, 0, 0, 0, 0])


tensor([2.2026e+04, 4.8517e+08, 1.0686e+13, 2.3539e+17, 5.1847e+21])


tensor([-10, -20, -30, -40, -50])


tensor([10, 20, 30, 40, 50])


In [ ]:
# прочие операции
tensor_4 = torch.Tensor([3, 6, 9, 12, 15, 18, 18])

print(torch.mean(tensor_4))
print("\n")

print(torch.std(tensor_4))
print("\n")

print(torch.max(tensor_4))
print("\n")

print(torch.min(tensor_4))
print("\n")

print(torch.prod(tensor_4))
print("\n")

print(torch.unique(tensor_4))
print("\n")

print(torch.sum(tensor_4))
print("\n")

tensor_5 = torch.tensor([3, 6, 9, 11, 15, 16, 18])
print(torch.eq(tensor_4, tensor_5))

tensor(11.5714)


tensor(5.8554)


tensor(18.)


tensor(3.)


tensor(9447840.)


tensor([ 3.,  6.,  9., 12., 15., 18.])


tensor(81.)


tensor([ True,  True,  True, False,  True, False,  True])


In [ ]:
# матричные операции
tensor_matrix_1 = torch.tensor([[10, 20], [30, 40]])
tensor_matrix_2 = torch.tensor([[50, 60], [70, 80]])

print(tensor_matrix_1)
print(tensor_matrix_1.T)
print(torch.transpose(tensor_matrix_1, 0, 1))
print(torch.matmul(tensor_matrix_1, tensor_matrix_2))

tensor_vector_1 = torch.tensor([10, 20, 30, 40, 50, 60])
tensor_vector_2 = torch.tensor([70, 80, 90, 100, 110, 120])

tensor([[10, 20],
        [30, 40]])
tensor([[10, 30],
        [20, 40]])
tensor([[10, 30],
        [20, 40]])
tensor([[1900, 2200],
        [4300, 5000]])


In [ ]:
# перенос тензоров на GPU с помощью метода to() и атрибута device
test_tensor = torch.randn(100)
test_tensor.device

device(type='cpu')

In [ ]:
test_tensor = test_tensor.to(device="cuda:0")
test_tensor.device

RuntimeError: ignored

## Задания

1. Создайте одномерный PyTorch-тензор из списка Python длиной 100, где каждый элемент является квадратом его индекса (индексы начинаются с 0)
2. Вычислите у созданного в п. 1 тензора следующие функции: синус, косинус, возведение в степень 3, логарифм по основанию 10, экспонента, среднее (mean), стандартное отклонение (std), максимум и минимум
3. Перенесите созданный в п. 1 тензор на GPU
4. Создайте одномерный тензор с названием big_tensor, заполненный случайными числами от 0 до 1, и имеющий длину 1.000.000 Измерьте время выполнения следующей операции: `sin(tensor)^10` + `cos(tensor)^10` сперва на CPU, потом на GPU
5. Создайте два двумерных тензора (матрицы), заполненных случайными числами от 0 до 1 и имеющих размер 10000х10000. Измерьте время выполнения операции произведения этих матриц сперва на CPU, а потом на GPU

 # Задание 1

In [2]:
import random
import torch
# Создание списка из 100 случайных элементов
random_list = [random.random() for _ in range(100)]

# Применение квадрата индекса к каждому элементу списка с помощью enumerate
squared_index_list = [value * (index ** 2) for index, value in enumerate(random_list)]

# Преобразование в PyTorch тензор
torch_tensor = torch.tensor(squared_index_list)

torch_tensor

tensor([0.0000e+00, 7.5866e-01, 1.4874e+00, 7.4917e+00, 1.3963e+01, 1.3557e+01,
        1.9666e+01, 2.4933e+01, 4.3631e+01, 7.6116e+01, 8.1317e+01, 3.7965e+01,
        1.0696e+02, 1.4446e+02, 1.4261e+02, 1.3038e+02, 1.0196e+02, 2.7711e+02,
        2.1609e+02, 1.9220e+02, 2.0820e+02, 4.2475e+02, 2.6401e+02, 3.0930e+02,
        3.3224e+02, 5.5300e+02, 6.2444e+02, 6.9151e+02, 7.0196e+02, 6.1776e+02,
        7.1534e+01, 5.1497e+02, 1.0001e+03, 2.4438e+02, 2.4008e+02, 1.0865e+02,
        1.1340e+03, 1.1036e+03, 1.0765e+03, 8.3691e+02, 4.4202e+02, 1.3738e+02,
        9.3147e+02, 1.2419e+03, 6.5749e+01, 9.5598e+02, 5.1369e+02, 1.9738e+03,
        1.9626e+03, 2.0479e+03, 1.8050e+03, 1.3438e+02, 2.1299e+01, 2.3243e+03,
        2.2278e+03, 1.1319e+03, 7.8234e+02, 2.9356e+03, 7.4501e+02, 1.3031e+03,
        3.4141e+03, 2.7513e+03, 3.3069e+03, 1.6439e+03, 2.7934e+03, 2.0446e+03,
        2.5065e+03, 1.2910e+03, 3.9545e+02, 3.2643e+03, 4.0076e+03, 1.3196e+02,
        2.8637e+03, 1.7826e+03, 4.9648e+

# Задание 2

In [12]:
# Вычисление различных функций для тензора
sin_tensor = torch.sin(torch_tensor)
cos_tensor = torch.cos(torch_tensor)
pow_tensor = torch_tensor ** 3
log_tensor = torch.log10(torch_tensor + 1e-9)  # Добавляем небольшое число для избежания log(0)
exp_tensor = torch.exp(torch_tensor)


# Вычисление статистических метрик
mean_val = torch.mean(torch_tensor)
std_val = torch.std(torch_tensor)
max_val = torch.max(torch_tensor)
min_val = torch.min(torch_tensor)


print(f'Синусы: {sin_tensor}')
print(f'Косинусы: {cos_tensor}')
print(f'Возведение в 3 степень: {pow_tensor}')
print(f'Логарифмы по основанию 10: {log_tensor}')
print(f'Экспоненты: {exp_tensor}')
print(f'Среднее: {mean_val}')
print(f'Стандартное отклонение: {std_val}')
print(f'Максимум: {max_val}')
print(f'Минимум: {min_val}')

Синусы: tensor([ 0.0000,  0.6879,  0.9965,  0.9351,  0.9848,  0.8364,  0.7285, -0.1987,
        -0.3438,  0.6576, -0.3564,  0.2632,  0.1448, -0.0519, -0.9454, -1.0000,
         0.9907,  0.6051,  0.6307, -0.5327,  0.7535, -0.5939,  0.1131,  0.9889,
        -0.6986,  0.0844,  0.6696,  0.3496, -0.9832,  0.9047,  0.6615, -0.2486,
         0.8561, -0.6186,  0.9692,  0.9643,  0.1178, -0.7644,  0.8984,  0.9490,
         0.8103, -0.7488,  0.9999, -0.8064,  0.2223,  0.8050, -0.9991,  0.7869,
         0.7833, -0.4203,  0.9846,  0.6508,  0.6385, -0.4609, -0.4320,  0.8237,
        -0.0814,  0.9753, -0.4346,  0.6131,  0.7099, -0.7061,  0.9181, -0.7697,
        -0.4729,  0.5760, -0.4535,  0.1484, -0.3769, -0.2031, -0.8633,  0.0082,
        -0.9848, -0.9707,  0.1045, -0.9907, -0.9950, -0.8178,  0.3305,  0.9037,
         0.2024, -0.9431,  0.9871, -0.6463, -0.5885, -0.5514,  0.9815, -0.0733,
        -0.5589,  0.8921,  0.7369,  0.8937, -0.9954, -0.4058, -0.9987, -0.8922,
         0.9222, -0.1202,  0.680

# Задание 3

In [13]:
if torch.cuda.is_available():
	torch_tensor_gpu = torch_tensor.to('cuda')
	result = "Тензор успешно перенесен на GPU."
else:
	result = "GPU не доступен."

result

'Тензор успешно перенесен на GPU.'

# Задание 4

In [17]:
import time

big_tensor = torch.rand(1000000)

# Выполнение операции на CPU и измерение времени
start_time_cpu = time.time()
result_cpu = torch.sin(big_tensor)**10 + torch.cos(big_tensor)**10
end_time_cpu = time.time()
tensor_cpu_time = end_time_cpu - start_time_cpu

# Перенос тензора на GPU и выполнение операции на GPU
if torch.cuda.is_available():
	big_tensor_gpu = big_tensor.to('cuda')
	start_time_gpu = time.time()
	result_gpu = torch.sin(big_tensor_gpu) ** 10 + torch.cos(big_tensor_gpu) ** 10
	end_time_gpu = time.time()
	tensor_gpu_time = end_time_gpu - start_time_gpu
else:
	tensor_gpu_time = "GPU не доступен."

print(f'Время выполнения операции нв CPU: {tensor_cpu_time}')
print(f'Время выполнения операции нв GPU: {tensor_gpu_time}')

Время выполнения операции нв CPU: 0.00954890251159668
Время выполнения операции нв GPU: 0.004005908966064453


# Задание 5

In [18]:
# Создание двух двумерных тензоров (матриц)
matrix1 = torch.rand(10000, 10000)
matrix2 = torch.rand(10000, 10000)

# Выполнение операции матричного умножения на CPU и измерение времени
start_time_cpu = time.time()
result_cpu = torch.matmul(matrix1, matrix2)
end_time_cpu = time.time()
matrix_cpu_time = end_time_cpu - start_time_cpu

# Перенос матриц на GPU и выполнение операции (если доступен)
if torch.cuda.is_available():
	matrix1_gpu = matrix1.to('cuda')
	matrix2_gpu = matrix2.to('cuda')
	torch.cuda.synchronize()  # Дождаться переноса матриц на GPU

	start_time_gpu = time.time()
	result_gpu = torch.matmul(matrix1_gpu, matrix2_gpu)
	torch.cuda.synchronize()  # Дождаться завершения операции
	end_time_gpu = time.time()

	matrix_gpu_time = end_time_gpu - start_time_gpu
else:
	matrix_gpu_time = "GPU не доступен."

print(f'Время выполнения операции нв CPU: {matrix_cpu_time}')
print(f'Время выполнения операции нв GPU: {matrix_gpu_time}')

Время выполнения операции нв CPU: 5.686149835586548
Время выполнения операции нв GPU: 2.130129098892212
